# Generated by Django 4.1.7 on 2023-04-07 06:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_user_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(max_length=255, verbose_name="Password"),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                max_length=255, unique=True, verbose_name="Username"
            ),
        ),
    ]
