# Generated by Django 4.1.7 on 2023-03-29 13:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"ordering": ["id"]},
        ),
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(max_length=40, verbose_name="Password"),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(max_length=20, unique=True, verbose_name="Username"),
        ),
    ]
