#!/bin/sh
sudo apt update
sudo apt install python3-venv python3-dev libpq-dev postgresql postgresql-contrib nginx curl python3-pip
cd ~
git clone https://github.com/Emmanuel289/Travit && cd Travit
python3 -m venv projectenv

# source projectenv/bin/activate
pip install psycopg2-binary gunicorn
pip install -r travit_service/requirements.txt
touch ~/Travit/travit_service/travit_service/server_settings
cd ~/Travit/travit_service/travit_service/


echo """
# Add domain name and public DNS, and server ip address to allowed hosts

ALLOWED_HOSTS = []

# Set postgresql as the database
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': '',
        'USER': '',
        'PASSWORD': '',
        'HOST': '',
        'PORT': '',
    }
}
""" > server_settings.py

# Complete initial project setup
python3 ~/Travit/travit_service/manage.py makemigrations
python3 ~/Travit/travit_service/manage.py migrate
python3 ~/Travit/travit_service/manage.py collectstatic
cd ~/Travit/travit_service
sudo ufw allow 8000

# Configure and test gunicorn
# gunicorn --bind 0.0.0.0:8000 travit_service.wsgi
deactivate

# Creating systemd socket and service files for Gunicorn
sudo touch /etc/systemd/system/gunicorn.socket
sudo touch /etc/systemd/system/gunicorn.service


sudo echo """
[Unit]
Description=gunicorn socket

[Socket]
ListenStream=/run/gunicorn.sock

[Install]
WantedBy=sockets.target
""" > /etc/systemd/system/gunicorn.socket

sudo echo """
[Unit]
Description=gunicorn daemon
Requires=gunicorn.socket
After=network.target

[Service]
User=ubuntu
Group=www-data
WorkingDirectory=/home/ubuntu/Travit/travit_service
ExecStart=/home/ubuntu/Travit/projectenv/bin/gunicorn \
          --access-logfile - \
          --workers 3 \
          --bind unix:/run/gunicorn.sock \
          travit_service.wsgi:application

[Install]
WantedBy=multi-user.target
""" >> /etc/systemd/system/gunicorn.service

sudo systemctl start gunicorn.socket
sudo systemctl enable gunicorn.socket

# Check for Gunicorn Socket File
sudo systemctl status gunicorn.socket
file /run/gunicorn.sock

# Error checks for gunicorn socket
sudo journalctl -u gunicorn.socket

# Testing socket activation
sudo systemctl status gunicorn
# curl --unix-socket /run/gunicorn.sock localhost
# sudo systemctl status gunicorn

# Error checks for gunicorn service
sudo journalctl -u gunicorn
# sudo systemctl daemon-reload
# sudo systemctl restart gunicorn

# Configure Nginx to Proxy Pass to Gunicorn
sudo touch /etc/nginx/sites-available/travit

echo """
server {
    listen 80;
    server_name 35.182.203.174;
     location = /favicon.ico { access_log off; log_not_found off; }
    location /static/ {
        root /home/ubuntu/Travit/travit_service;
    }

    location / {
        include proxy_params;
        proxy_pass http://unix:/run/gunicorn.sock;
    }
}
""" > /etc/nginx/sites-available/travit
sudo ln -s /etc/nginx/sites-available/travit /etc/nginx/sites-enabled

sudo nginx -t # test nginx for syntax errors
sudo systemctl restart nginx
sudo ufw delete allow 8000
sudo ufw allow 'Nginx Full'
