name: Build Python App

on:
  release:
    types: [published]

jobs:
  release-build:
    runs-on: ubuntu-latest

    steps:
        - name: Checkout repository
          uses: actions/checkout@v5

        - name: Setup Python
          uses: actions/setup-python@v5
          with:
            python-version: "3.12"

        - name: Build release distribution
          run: |
            echo "Building release distribution for Python app"
            bash -c ./service/scripts/build_packages python
