name: Deploy to Staging Environment
'on':
  push:
    branches:
      - develop
jobs:
  build_and_deploy_to_staging:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run:  cd travit && npm ci && npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          entryPoint: 'travit'
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_TRAVIT_E0E79 }}'
          channelId: staging
          projectId: travit-staging
