name: Push to ECR
on: 
  push: 
    branches:
      - main
jobs:
  push_to_ecr:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'This action will push the image to ECR'
      - name: Checkout repository code
        uses: actions/checkout@v2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ca-central-1
      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1
      - name: Build, tag, and push image to Amazon ECR
        run: |
          aws ecr get-login-password --region ca-central-1 | docker login --username AWS --password-stdin 784757923335.dkr.ecr.ca-central-1.amazonaws.com
          cd travit_ui
          docker build -t travit-ui-test .
          docker tag travit-ui-test:latest public.ecr.aws/q9z9h3p6/travit-ui-test:latest
          docker push public.ecr.aws/q9z9h3p6/travit-ui-test:latest
      
