name: Push to ECR
on: 
  push: 
    branches:
      - main
jobs:
  push_to_ecr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v2
      - name: Login to ECR
          aws ecr get-login-password --region ca-central-1 | docker login --username AWS --password-stdin 784757923335.dkr.ecr.ca-central-1.amazonaws.com
      - name: Build, tag, and push image to Amazon ECR
        run: |
          cd travit_ui
          docker build -t travit-ui-test .
          docker tag travit-ui-test:latest 784757923335.dkr.ecr.ca-central-1.amazonaws.com/travit-ui-test:latest
          docker push 784757923335.dkr.ecr.ca-central-1.amazonaws.com/travit-ui-test:latest
      
