name: "Test Python App"

on:
  pull_request:
    branches: ["main"]

permissions:
  contents: read


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Python 3.12
        uses: actions/setup-python@v3
        with:
            python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m venv .venv
          python -m pip install -U pip
          source .venv/bin/activate
          echo "pytest" > requirements-test.txt
          python -m pip install -r requirements-test.txt

      - name: Test with pytest
        run: |
            pytest
