name: Run UI Server
on:
  pull_request:
  push:
    branches: 'develop'
jobs:
  run-travit-ui:
    runs-on: ubuntu-latest
    steps:
      outputs: 
        backend: ${{ steps.working-directory.outputs.backend }}
        frontend: ${{ steps.output.working-directory.outputs.frontend}}
      - name: Checkout repository code
        uses: actions/checkout@v2
      - uses: dorny/paths-filter@v2
        id: working-directory
        with:
          filters: |
            backend: 
              - 'travit_backend'
            frontend:
              - 'travit_ui'
      - name: Test on backend
        if: steps.working-directory.outputs.backend == 'true'
        run: echo 'This is the backend folder'

      - name: Test on frontend
        if: steps.working-directory.outputs.frontend == 'true':
        run: echo 'This is the frontend folder'

      - name: Build image
        run: | 
          cd travit_ui
          docker build -t travit-ui-test -f Dockerfile .
          echo 'Displaying images'
          docker images
      - name: Run container
        run: |
          docker run -dp 3000:3000 travit-ui-test
          
        
