name: Run UI Server
on:
  pull_request:
jobs:
  run-travit-ui:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v2
      - name: Build image
        run: | 
          cd travit_ui
          docker build -t travit-ui-test -f Dockerfile .
          echo 'Displaying images'
          docker images
      - name: Run container
        run: |
          docker run -dp 3000:3000 travit-ui-test
          
        
