name: Run UI Server
on:
  push:
    branches:
      - develop
      - main

jobs:
  run-travit-ui:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'This action will build the image for the ui and run the ui server'
      - name: Checkout repository code
        uses: actions/@checkoutv2
      - name: Build UI image
      - run: docker build -t travit-test -f Dockerfile .
