name: Run UI Server
on:
  push:
    branches:
      - develop
      - main

jobs:
  run-travit-ui:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'This action will build the image for the ui and run the ui server'
      - name: Checkout repository code
        uses: actions/checkout@v2
      - name: Build image
        run: | 
          cd travit_ui
          docker build -t travit-test -f Dockerfile .
      - name: Show image builds
      - run: |
          docker images
      - name: Run container
      - run: |
          docker run -dp 4200:3000 travit:test
          curl localhost:4200
          
        
