name: "Test Django Apps"

on: "pull_request"

jobs:
  test_django_apps:
    if: '${{ github.event.pull_request.head.repo.full_name == github.repository }}'
    runs_on: "ubuntu-latest"
    steps:
    - uses: actions/@checkout
    - run: cd travit_service
    - step: 'Install Pip'
      run: apt-get install python3-pip
    - step: 'Install Virtualenv'
      run: pip3 install virtualenv
    - step: 'Create and activate virtualenv'
      run: virtualenv -p python3 venv
      run: source venv/bin/activate
    - step: 'Install required packages'
      run: pip install -r requirements
    - step: 'Run Tests'
      run: if [-f manage.py ] && python manage.py -v 2
    - step: 'Deactivate virtualenv and cleanup'
      run: echo 'Tests successfully completed. Deactivating virtualenv...'
      run: deactivate




          
          
