# The name of this workflow
name: Test Django Apps

# The events that trigger this workflow
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

# The jobs that run in this workflow
jobs:
  setup:  # The name of this job
    strategy:
      matrix:
        # Run this job for each combination of python and ubuntu versions
        python-version: [3.11, 3.12, 3.13]
        ubuntu-version: [ubuntu-22.04, ubuntu-24.04]
    runs-on: ${{ matrix.ubuntu-version }}

    # The steps that are executed in this job
    steps:
      # Clone this repo
      - name: Checkout # The name of this step
        uses: actions/checkout@v5.0.0 # This step uses the checkout action which is used for checking out git repositories

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

  test:
    strategy:
      matrix:
        ubuntu-version: [ubuntu-22.04, ubuntu-24.04]
    runs-on: ${{ matrix.ubuntu-version }}
    needs: setup # This job depends on the setup job to complete successfully

    steps:
      # Clone this repo
      - name: Checkout
        uses: actions/checkout@v5.0.0

    # Run tests
      - name: Run tests
        env:
          SCRIPTS_DIR: ./service/scripts
          CONFIG_FILE_PATH: ./service/config/config.yaml"
          PROJECT_DIR: ./service/
        run: |
          set -e

          echo "The project settings are stored in the config file -> ${CONFIG_FILE_PATH}"
          echo "Setting up environment to run tests."
          source "${SCRIPTS_DIR}/setup_env.sh"
          echo "Running all tests in the project '${PROJECT_DIR}'."
          bash "${SCRIPTS_DIR}/run_tests.sh"
